### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to Spamkiller v1.0.3 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by antibitcoin** [Kuraky/Spamkiller#1]
[07:25:25 ERROR]: Could not pass event AsyncPlayerChatEvent to Spamkiller v1.0.3
java.lang.NullPointerException: null

Paper 1.16.5 
plugin version
1.0.3

this error is spamming console non stop, sometimes the plugin works sometimes now.

Help please

**Comment by Kuraky** [comment]
Could you send the entire error message?
If you can't see it, check your latest.log file. 
The entire error message should look similar to this:
![obraz](https://user-images.githubusercontent.com/38810662/115788945-a873a200-a3c4-11eb-8ab7-88c5b7c86574.png)

**Comment by Kuraky** [comment]
Ok, I managed to find the issue. I'll be recoding the entire plugin as this is the third time something broke completly in the plugin and I'm not able to find a clear reason why.
